configs:
  - id: log-ingest-k8s-namespace
    config:
      name: "log-ingest-k8s-namespace"
      template: template.json
      parameters:
        namespace: "test-namespace"        # EDIT: target k8s namespace
    type:
      settings:
        schema: builtin:logmonitoring.log-storage-settings
        scope: environment
