services:
  petclinic:
    build:
      context: .
      args:
        - DT_PAAS_TOKEN=${DT_PAAS_TOKEN}
    image: petclinic:local
    container_name: petclinic
    ports:
      - "8090:8080"
    environment:
      - JAVA_TOOL_OPTIONS=-agentpath:/opt/dynatrace/oneagent/agent/lib64/liboneagentproc.so
    restart: unless-stopped
