configs:
  - id: update-window-weekly
    config:
      name: update-window-weekly
      template: template.json
      parameters:
        windowName:
          type: environment
          name: WINDOW_NAME
          default: "POC Update Window"
    type:
      settings:
        schema: builtin:deployment.management.update-windows
        scope: environment
