configs:
  - id: host-cpu-alert
    config:
      name: host-cpu-alert
      template: template.json
      parameters:
        alertTitle:
          type: environment
          name: ALERT_TITLE
          default: "POC Host CPU Alert"
    type:
      settings:
        schema: builtin:davis.anomaly-detectors
        scope: environment
